import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Kapakana, Mona_Sans, Stalemate, Domine } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const kapakana = Kapakana({ 
  subsets: ["latin"], 
  variable: "--font-kapakana" 
});

const stalemate = Stalemate({ 
  subsets: ["latin"], 
  weight: ["400"], 
  variable: "--font-stalemate" 
});

const monaSans = Mona_Sans({ 
  subsets: ["latin"], 
  variable: "--font-mona" 
});

const domine = Domine({ 
  subsets: ["latin"], 
  weight: ["400", "700"], 
  variable: "--font-domine" 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "You are invited",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kapakana.variable} ${stalemate.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
